name: Publish to JSR

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  # Run CI first to ensure code quality
  ci:
    uses: ./.github/workflows/ci.yml
    
  publish:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: ci  # Only run if CI passes

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.4.0

      - name: Create deno.json for JSR
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION="${{ github.event.inputs.version || github.ref_name }}"
          VERSION=${VERSION#v}
          
          cat > deno.json << EOF
          {
            "name": "@aidevtool/tmux-monitor",
            "version": "$VERSION",
            "exports": "./mod.ts"
          }
          EOF

      - name: Publish to JSR
        run: deno publish --allow-dirty